### PR TITLE
unary $ for path interpolation

### PR DESCRIPTION
**Pull request by mmjconolly**
Fixes https://github.com/sifive/wake/issues/606

### CODE REVIEW

**Comment by terpstra** [comment]
What do other people think about this change?

Dedicating a single-character operator for this seems a bit spendy for this convenience. What I like about `getPathName` is it very clearly says what's happening. OTOH, I agree it comes up a lot.

**Comment by mwachs5** [comment]
is it really dedicating it ONLY for paths? Couldn't we define a `$` for things that are not paths (say, integers)?

**Comment by mmjconolly** [comment]
I don't care if it's specifically `$` or something else, just something much shorter / less verbose than getPathName, since it's going to be used in a lot of Plans

**Comment by terpstra** [comment]
> is it really dedicating it ONLY for paths? Couldn't we define a `$` for things that are not paths (say, integers)?

In wake, you cannot have two different functions with the same name, like you can in scala (overloaded by type).

**Comment by terpstra** [comment]
Plan for now is to put something like this into our actual repositories and play around with it before promoting it into the standard library

**Pull request closed without merging**
