### PR TITLE
Sync master to 39.* releases

### PR DESCRIPTION
**Pull request by V-FEXrt**
Merges release-39.0.0 back into master which branch for various hotflixes. This will pull through the correct updates to the debian changelog

### CODE REVIEW

**Comment by V-FEXrt** [comment]
I'm not sure whats going on with the diff here. I'd expect only the changelog.in to be different since all the other changes where cherry-picked from master into the release branch

**Comment by JakeSiFive** [comment]
I think just do a normal release, no need to merge right?

**Comment by mmjconolly** [comment]
I'd have assumed all the patches that went out on the patch releases would have already been put in`master` branch

**Comment by V-FEXrt** [comment]
All the patches are already on `master` which is the strange part. The only thing not on master is the changes to `debian/changelog.in` that is what I want to pull back in

**Comment by V-FEXrt** [comment]
> I think just do a normal release, no need to merge right?

I'm not trying to do a release here, just trying to sync master and the release branch

**Comment by mmjconolly** [comment]
> All the patches are already on master which is the strange part

We'd expect that as we landed the PRs there first, before cherry-picking them into release branches

**Pull request closed without merging**
