### PR TITLE
Add non-unicode inline pair constructor

### PR DESCRIPTION
**Pull request by colinschmidt**
This is a nice to have since I don't have a `→` key on my keyboard.
I'm not sure if there is some other place to put functions that are just aliases, or if my syntax is correct here.

### CODE REVIEW

**Comment by terpstra** [comment]
So, the problem with proposal is that the precedence of `-` is far too high:

Try this code:
```
def foo = (
  "hello" -> 23 | str,
  "bye" -> "asd",
  Nil
)
```

**Comment by terpstra** [comment]
I suppose you could try `$->`, but that's right-associative vs `→` which is left-associative.

**Comment by terpstra** [comment]
I thought `:->` would be legal, but it seems it is not, currently. Normal type ascription is also right-associative, though, so even if we made it legal to define operators starting with `:`, we'd probably want `:->` to be right-associative too, for consistency.

**Comment by mmjconolly** [comment]
How far down the table of operators does it need to be, Below `OrOp` in https://github.com/sifive/wake/blob/master/share/doc/wake/quickref.md ?

Ill throw one out there: `$~~>`

**Comment by terpstra** [comment]
So, that table is out-of-date since the new parser. There are substantially less precedence levels now. I should update it.

FYI, only the first character of the operator matters. `$->` is the same as `$$~^>`.

**Pull request merged**
