### PR TITLE
Increase MAX_JSON from 1 MiB to 1 GiB

### PR DESCRIPTION
**Pull request by jackkoenig**

### CODE REVIEW

**Comment by jackkoenig** [comment]
Note this is against v0.15

**Comment by terpstra** [comment]
Doesn't 1GB seem a bit excessive?

**Comment by jackkoenig** [comment]
It’s a max so does it really matter? We can do 64 or 128 MiB if you prefer

**Comment by terpstra** [comment]
I'm going to fix this via #316 on master and then a cherry-pick to v0.15

**Pull request closed without merging**
