### PR TITLE
a .ctags file to create tags file for wake

### PR DESCRIPTION
**Pull request by sistillson**
Not perfect, or minimal, but effective.

### CODE REVIEW

**Comment by terpstra** [comment]
Sorry for my ignorance, but what does this do?

**Comment by sistillson** [comment]
It creates a file that vi can read, tags, that you can use to jump to definitions.

**Comment by terpstra** [comment]
What does this do for:
```
def x +++ y = x + y
```

It looks like it would consider this a definition of 'x', not '+++'?

**Comment by sistillson** [comment]
That is correct. it's far from perfect. I wasn't sure

**Comment by sistillson** [comment]
i'm trying to figure it out right now

**Pull request closed without merging**
