### PR TITLE
fuse: use unshare to fully redact the workspace

### PR DESCRIPTION
**Pull request by terpstra**
Previously, fuse-wake provided a redacted view of the workspace on
.fuse/pid/ and ran Jobs there. This has two downsides:

- we trust the Job not to access the workspace directly
- the Jobs can notice that .fuse is in the build paths
  - this can result in non-deterministic output
  - this can confuse follow-on Jobs that expect .fuse filenames

This change only affects linux

### CODE REVIEW

**Comment by terpstra** [comment]
Fixes #439 
Fixes #443

**Comment by mmjconolly** [comment]
> I was going to ask whether unshare works on CentOS 7, but I remember that the CI tests for this repo test CentOS 6 and 7, so this LGTM! FWIW, CentOS 7 runs kernel version 3.10.

I don't think the CI tests here are representative of what a real OS would do, as they're using the container-runtime's kernel

**Comment by terpstra** [comment]
Also, they are using the preload runner, not fuse.

**Comment by terpstra** [comment]
Let me turn off the preload runner and see what happens.

**Comment by terpstra** [comment]
My guess is this will just fail because FUSE is not enabled on these servers...

**Comment by mmjconolly** [comment]
> My guess is this will just fail because FUSE is not enabled on these servers...

I think the FUSE wont have permission as it's already in an unshare being in a container

**Comment by richardxia** [comment]
> I don't think the CI tests here are representative of what a real OS would do, as they're using the container-runtime's kernel

Yes, good point; I forgot about that.

I slightly regret bringing this up at all, since it might be more work than is worth it to try to make this work on CircleCI. I think testing it locally on Ubuntu 16.04 is sufficient.

**Comment by bsousi5** [comment]
Wes, if you could get this in sooner, it would be great. We are hitting this issue when we need to rebuild wake test | ipdelivery after failure on gamma servers

**Comment by terpstra** [comment]
Rebased this against the new CI. I'll add network and directory isolation in follow-up PRs.

**Comment by richardxia** [comment]
Thanks! This is going to help with a lot of stuff!

**Pull request merged**
