### PR TITLE
Minor changes to timeline and licenses

### PR DESCRIPTION
**Pull request by elena-pudovkina**
Timeline code is cleaned and sped up.
Years and misprints in licenses are corrected.

### CODE REVIEW

**Review by JakeSiFive — APPROVED** [review]
LGTM

**Comment by JakeSiFive** [comment]
wait no I take it back, we want 2022 not 2021...that always takes getting used to

**Comment by elena-pudovkina** [comment]
> wait no I take it back, we want 2022 not 2021...that always takes getting used to

It does!

**Review by terpstra — APPROVED** [review]

**Comment by JakeSiFive** [comment]
Uh this got merged without the requested change to 2022 btw

**Comment by elena-pudovkina** [comment]
> Uh this got merged without the requested change to 2022 btw

Ah, I misinterpreted your comment. The lsp stuff was written in 2021

**Comment by JakeSiFive** [comment]
Not a big deal but the advice that has been handed down to me from lawyers is that it should be the date of first publication not the date of authorship. So if these were previously published in 2021 then this is correct but generally when something is added in review in 2022 we want to use 2022....this probably won't matter again until 2023 but just FYI for next time!

**Pull request merged**
