### PR TITLE
Rename formatter() to fmt()

### PR DESCRIPTION
**Pull request by V-FEXrt**

### CODE REVIEW

**Review by JakeSiFive — APPROVED** [review]

**Comment by JakeSiFive** [comment]
omg its another macos day....ahhhhh I hate this

**Comment by ag-eitilt** [comment]
I think that's the effect they were going for. 😉

**Comment by JakeSiFive** [comment]
TBH, this is my favorite way to deprecate things but only if you provide an alternative and they have not provided us an alternative.

**Comment by JakeSiFive** [comment]
please kick this

**Pull request merged**
